ATB-1246 | Set up custom namespace metrics to be sent to Dynatrace
govuk-one-login/ais-infra pull request #5
Opened 2024-01-05 16:03 UTC by MinaMahdi

### What ?

Creating a CloudFormation template to deploy resources that will enable the Dynatrace integration with Amazon CloudWatch Metric Streams to ingest AWS metrics for the custom metric namespace Account Interventions Service .

### Why? 

To allow us to view our Account Interventions Service metrics in Dynatrace. 

Testing: 
![Screenshot 2024-01-05 at 15 55 11](https://github.com/govuk-one-login/ais-infra/assets/116737136/7312a92f-d204-4536-81cc-ea3e0ace08b9)

Notes:

- Account Interventions Service custom metrics will be appear once the main pipeline runs.
- To be deployed all the way to Production, however, must note that will need to generate a Dynatrace Api Key (Joe Roberts) specifically for Production to be added as the value for DynatraceApiKey secret.

2024-01-05 16:42 UTC, TaherKapasi requested changes
Same comments from other PR

2024-01-05 17:09 UTC, liamquayle approved these changes

2024-01-08 09:40 UTC, chiarapascucci-gds approved these changes

2024-01-08 10:02 UTC, amd-gds approved these changes

2024-01-08 10:10 UTC, TaherKapasi approved these changes

2024-01-08 11:17 UTC, merged